version: 2.1

orbs:
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
